FROM alpine:3.13 AS verify

RUN apk add --no-cache bash tar xz
ARG ROOTFS=rootfs.tar.xz

COPY ${ROOTFS} ./${ROOTFS}
RUN mkdir -p /rootfs
RUN tar -xf ${ROOTFS} -C /rootfs

FROM scratch AS test
COPY --from=verify /rootfs/ /

RUN apk update \
    && apk upgrade \
    && apk add python3 \
    && python3 -V

FROM scratch AS root
COPY --from=verify /rootfs/ /

ENV LANG=en_US.UTF-8
CMD ["/usr/bin/bash"]

