FROM alpine:3.13 AS verify

#RUN pacman -Syu
ARG ROOTFS=rootfs.tar.xz

COPY ${ROOTFS} ./${ROOTFS}
RUN mkdir -p /rootfs
RUN tar -xf ${ROOTFS} -C /rootfs

FROM scratch AS test
COPY --from=verify /rootfs/ /

RUN pacman -Syu --noconfirm \
    && pacman -S python3 --noconfirm \
    && python3 -V

FROM scratch AS root
COPY --from=verify /rootfs/ /

ENV LANG=en_US.UTF-8
CMD ["/usr/bin/bash"]

